name: Deploy to Google Cloud Run, AWS Fargate, and AWS SageMaker

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_SERVICE: air-quality-forecast
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_REPOSITORY: ${{ secrets.GCP_ARTIFACT_REPOSITORY }}

  AWS_REGION: us-west-2
  ECR_REPOSITORY_PREPARE: air-quality-forecast-prepare
  ECS_TASK_DEFINITION: air-quality-forecast-prepare-task
  CONTAINER_NAME: prepare-container

  ECR_REPOSITORY_TRAIN: air-quality-forecast-train

jobs:
  deploy-cloud-run:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    environment: gcp
    permissions:
      contents: 'read'
      id-token: 'write'
    if: "!contains(github.event.head_commit.message, '[skip-gcp]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}

      - run: |-
          gcloud --quiet auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build (Cloud Run)
        run: |-
          docker build \
            --tag "${{ env.GCP_REGION }}-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/$GCP_SERVICE:$GITHUB_SHA" \
            .  # Builds from the root Dockerfile (for app.py)

      - name: Push (Cloud Run)
        run: |-
          docker push "${{ env.GCP_REGION }}-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/$GCP_SERVICE:$GITHUB_SHA"

      - name: Deploy (Cloud Run)
        run: |-
          gcloud run deploy "$GCP_SERVICE" \
            --image "${{ env.GCP_REGION }}-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_REPOSITORY/$GCP_SERVICE:$GITHUB_SHA" \
            --region "$GCP_REGION" \
            --platform "managed" \
            --allow-unauthenticated \
            --memory=2Gi \
            --timeout=120s \
            --set-env-vars="OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }},AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }},AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }},S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}"

  deploy-fargate:
    name: Deploy prepare.py to AWS Fargate
    runs-on: ubuntu-latest
    environment: aws-fargate
    if: "!contains(github.event.head_commit.message, '[skip-fargate]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_PREPARE:$IMAGE_TAG -f prepare/Dockerfile prepare/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_PREPARE:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY_PREPARE:$IMAGE_TAG"

      - name: Render Amazon ECS Task Definition
        id: render-task-definition
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: prepare/task-definition.json
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Register Task Definition
        id: register-task-def
        run: |
          aws ecs register-task-definition --cli-input-json file://prepare/task-definition.json
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


  deploy-sagemaker:
    name: Deploy train.py to AWS SageMaker
    runs-on: ubuntu-latest
    environment: aws-sagemaker
    if: "!contains(github.event.head_commit.message, '[skip-sagemaker]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr-train
        uses: aws-actions/amazon-ecr-login@v1

      - name: Authenticate Docker to Pull Base Image
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin 763104351884.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build, tag, and push train image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-train.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_TRAIN:$IMAGE_TAG -f train/Dockerfile train/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_TRAIN:$IMAGE_TAG
          echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY_TRAIN:$IMAGE_TAG" >> $GITHUB_ENV

  deploy-all:
    name: Deploy All Services
    runs-on: ubuntu-latest
    needs: [deploy-cloud-run, deploy-fargate, deploy-sagemaker]
    steps:
      - name: Deployment Complete
        run: echo "All services deployed successfully!"