name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: air-quality-forecast # The name of your Cloud Run service
  REGION: ${{ secrets.GCP_REGION }} # Change to your desired region, must be the same as the Artifact Registry's
  REPOSITORY: ${{ secrets.GCP_ARTIFACT_REPOSITORY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Configure Docker to use the gcloud credential helper
      - run: |-
          gcloud --quiet auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # Build the Docker image
      - name: Build
        run: |-
          docker build \
            --tag "${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA" \
            .

      # Push the Docker image to Google Artifact Registry
      - name: Push
        run: |-
          docker push "${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA"

      # Deploy to Cloud Run
      - name: Deploy
        run: |-
          gcloud run deploy "$SERVICE" \
            --image "${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA" \
            --region "$REGION" \
            --platform "managed" \
            --allow-unauthenticated \
            --memory=2Gi \
            --startup-timeout=120s